package com.leetcode.innertransfer;

import java.util.HashMap;

/**
 * Given two strings s and t which consist of only lowercase letters.
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * Find the letter that was added in t.

 * Created by Yan on 9/19/16.
 */
public class E389_FindTheDifference {
    public static char findTheDifference(String s, String t) {
        HashMap<Character, Integer> map = new HashMap<>();
        for (int i = 0; i < s.length(); i++) {
            char c = s.charAt(i);
            if (map.containsKey(c))
                map.put(c, map.get(c) + 1);
            else
                map.put(c, 1);
        }
        for (int i = 0; i < t.length(); i++) {
            char c = t.charAt(i);
            if (!map.containsKey(c) || map.get(c) == 0)
                return c;
            else
                map.put(c, map.get(c) - 1);
        }
        return ' ';
    }

    public static char findTheDifferenceXor(String s, String t) {
        char result = t.charAt(t.length() - 1);
        for (int i = 0; i < s.length(); i++) {
            result ^= s.charAt(i) ^ t.charAt(i);
        }
        return result;
    }

    public static void main(String[] args) {
        String s = "abcd";
        String t = "aabcd";
        System.out.println(findTheDifference(s, t));
        System.out.println(findTheDifferenceXor(s, t));
    }
}
